name: CI

# Controls when the action will run. 
on: [push]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # depth 0 will download all the repository history
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # This will delete roassal and numeric scales and it executes the tests again
      - name: Run pharo Tests
        id: tests
        uses: akevalion/PharoTestsAction@v1
        with:
          baseline: 'Time' #BaselineOfTime
          #group: 'Full'#default
          tests: 'TimeExample'
          pharo: 'pharo11'